name: Gradle build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: gradle/gradle-build-action@v1
        with:
          arguments: build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            "old-app/build/reports/tests/**"
            "new-app/build/reports/tests/**"
